Extension { #name : #TUILibrary }

{ #category : #'*Toast-Dev' }
TUILibrary class >> deployFiles [
	<script>
	super deployFiles
]

{ #category : #'*Toast-Dev' }
TUILibrary class >> filesDirectory [
	^ GitTUI resources
]

{ #category : #'*Toast-Dev' }
TUILibrary class >> importFiles [
	<script>
	super importFiles
]

{ #category : #'*Toast-Dev' }
TUILibrary class >> openImportButton [
	<script>
	super openImportButton
]
